from __future__ import annotations

import re
import time
from collections import deque
from pathlib import Path
from typing import Any, Iterable

from google.cloud import resourcemanager_v3
from google.iam.v1 import iam_policy_pb2

from gcpwn.core.console import UtilityTools
from gcpwn.core.utils.iam_permissions import call_test_iam_permissions
from gcpwn.core.utils.action_recording import record_permissions as record_action_permissions
from gcpwn.core.utils.module_helpers import extract_path_tail, module_data_file, read_lines
from gcpwn.core.utils.persistence import save_to_table
from gcpwn.core.utils.serialization import resource_to_dict
from gcpwn.core.utils.service_runtime import handle_service_error
from gcpwn.modules.gcp.iam.utilities.helpers import (
    folder_get_iam_policy,
    folder_set_iam_policy,
    organization_get_iam_policy,
    organization_set_iam_policy,
    project_get_iam_policy,
    project_set_iam_policy,
)


DEFAULT_TEST_IAM_BATCH_SIZE = 100
FAILED_PERMISSION_RECORD_BATCH_SIZE = 5
RESOURCE_MANAGER_BATCH_CALLS_PER_WINDOW = 5
RESOURCE_MANAGER_BATCH_WINDOW_SECONDS = 60
RESOURCE_MANAGER_FAILED_PERMISSION_CALLS_PER_WINDOW = 300
RESOURCE_MANAGER_FAILED_PERMISSION_WINDOW_SECONDS = 600
RESOURCE_MANAGER_RATE_LIMIT_RETRY_ATTEMPTS = 3
INVALID_PERMISSION_RE = re.compile(r"Permission\s+([^\s]+)\s+is not valid for this resource")


def _permission_file(filename: str) -> str:
    return module_data_file(__file__, "data", filename)


def _scripts_output_dir() -> Path:
    return Path(__file__).resolve().parents[4] / "scripts"


def _is_rate_limit_error(exc: Exception) -> bool:
    message = str(exc or "")
    markers = (
        "429 Quota exceeded",
        "RATE_LIMIT_EXCEEDED",
        "Too Many Requests",
        "quota metric",
    )
    return any(marker in message for marker in markers)


def _resource_state_label(value: Any) -> str:
    token = str(value or "").strip().upper()
    if token in {"", "NONE"}:
        return "UNKNOWN_STATE"
    if token in {"0", "STATE_UNSPECIFIED"}:
        return "STATE_UNSPECIFIED"
    if token in {"1", "ALIVE", "ACTIVE"}:
        return "ACTIVE"
    if token in {"2", "DELETE_REQUESTED"}:
        return "DELETE_REQUESTED"
    return str(value or "").strip() or "UNKNOWN_STATE"


def _persist_metadata_gcp(session, data_object: Any, resource_type: str) -> None:
    def _extras(_obj: Any, raw: dict[str, Any]) -> dict[str, Any]:
        if resource_type == "organization":
            return {"parent": "None", "project_id": "N/A", "type": "org"}
        if resource_type == "project":
            return {
                "parent": str(raw.get("parent") or ""),
                "project_id": str(raw.get("project_id") or ""),
                "type": "project",
            }
        if resource_type == "folder":
            return {
                "parent": str(raw.get("parent") or ""),
                "project_id": "N/A",
                "type": "folder",
            }
        return {}

    if_column_matches = ["project_id"] if resource_type == "project" else None
    save_to_table(
        session,
        "abstract_tree_hierarchy",
        data_object,
        extra_builder=_extras,
        if_column_matches=if_column_matches,
    )


def _dedupe_rows(rows: Iterable[dict[str, Any]], *, key_field: str = "name") -> list[dict[str, Any]]:
    ordered: list[dict[str, Any]] = []
    seen: set[str] = set()
    for row in rows or []:
        payload = resource_to_dict(row)
        key = str(payload.get(key_field) or "").strip()
        if not key or key in seen:
            continue
        seen.add(key)
        ordered.append(payload)
    return ordered


class FailedPermissionReportWriter:
    def __init__(self, *, output_dir: str | Path | None = None) -> None:
        self.base_dir = Path(output_dir) if output_dir else _scripts_output_dir()
        self.base_dir.mkdir(parents=True, exist_ok=True)
        self._initialized_resource_types: set[str] = set()
        self._seen_permissions: dict[str, set[str]] = {}

    def _debug_path(self, resource_type: str) -> Path:
        return self.base_dir / f"resourcemanager_{resource_type}_failed_permissions.txt"

    def _list_path(self, resource_type: str) -> Path:
        return self.base_dir / f"resourcemanager_{resource_type}_failed_permissions_list.txt"

    def prepare(self, resource_type: str) -> None:
        token = str(resource_type or "").strip()
        if not token or token in self._initialized_resource_types:
            return
        debug_path = self._debug_path(token)
        list_path = self._list_path(token)
        debug_path.write_text(
            "\n".join(
                [
                    "# Generated by enum_resources --record-failed-permissions",
                    f"# resource_type={token}",
                    f"# clean_permission_list={list_path.name}",
                    "# Streaming failures are appended below as they happen.",
                    "",
                    "# Failures",
                    "",
                ]
            )
            + "\n",
            encoding="utf-8",
        )
        list_path.write_text("", encoding="utf-8")
        self._initialized_resource_types.add(token)
        self._seen_permissions[token] = set()

    def record(self, *, resource_type: str, permission: str, resource_name: str, error: str) -> None:
        token = str(resource_type or "").strip()
        permission_token = str(permission or "").strip()
        if not token or not permission_token:
            return

        self.prepare(token)
        debug_path = self._debug_path(token)
        list_path = self._list_path(token)
        sanitized_error = " ".join(str(error or "").split())

        with debug_path.open("a", encoding="utf-8") as handle:
            handle.write(
                " | ".join(
                    part
                    for part in [
                        permission_token,
                        f"resource={resource_name}" if str(resource_name or "").strip() else "",
                        f"error={sanitized_error}" if sanitized_error else "",
                    ]
                    if part
                )
                + "\n"
            )

        seen_permissions = self._seen_permissions.setdefault(token, set())
        if permission_token not in seen_permissions:
            with list_path.open("a", encoding="utf-8") as handle:
                handle.write(permission_token + "\n")
            seen_permissions.add(permission_token)


def record_failed_permissions(
    failed_permissions: dict[str, dict[str, dict[str, Any]]],
    *,
    resource_type: str,
    resource_name: str,
    permissions: Iterable[str],
    error: str,
    report_writer: FailedPermissionReportWriter | None = None,
) -> None:
    resource_type_token = str(resource_type or "").strip()
    bucket = failed_permissions.setdefault(resource_type_token, {})
    for permission in permissions or []:
        token = str(permission or "").strip()
        if not token:
            continue
        entry = bucket.setdefault(token, {"count": 0, "resources": set(), "errors": set()})
        entry["count"] = int(entry.get("count", 0)) + 1
        if resource_name:
            entry.setdefault("resources", set()).add(resource_name)
        if error:
            entry.setdefault("errors", set()).add(error)
        if report_writer is not None:
            report_writer.record(
                resource_type=resource_type_token,
                permission=token,
                resource_name=resource_name,
                error=error,
            )


def merge_failed_permissions(
    destination: dict[str, dict[str, dict[str, Any]]],
    source: dict[str, dict[str, dict[str, Any]]],
) -> dict[str, dict[str, dict[str, Any]]]:
    for resource_type, permission_map in (source or {}).items():
        target_bucket = destination.setdefault(str(resource_type or "").strip(), {})
        for permission, details in (permission_map or {}).items():
            token = str(permission or "").strip()
            if not token:
                continue
            entry = target_bucket.setdefault(token, {"count": 0, "resources": set(), "errors": set()})
            entry["count"] = int(entry.get("count", 0)) + int((details or {}).get("count", 0))
            entry.setdefault("resources", set()).update((details or {}).get("resources", set()) or set())
            entry.setdefault("errors", set()).update((details or {}).get("errors", set()) or set())
    return destination


def write_failed_permission_reports(
    failed_permissions: dict[str, dict[str, dict[str, Any]]],
    *,
    output_dir: str | Path | None = None,
) -> dict[str, str]:
    base_dir = Path(output_dir) if output_dir else _scripts_output_dir()
    base_dir.mkdir(parents=True, exist_ok=True)

    written_paths: dict[str, str] = {}
    for resource_type in sorted(failed_permissions.keys()):
        bucket = failed_permissions.get(resource_type) or {}
        if not bucket:
            continue
        path = base_dir / f"resourcemanager_{resource_type}_failed_permissions.txt"
        list_path = base_dir / f"resourcemanager_{resource_type}_failed_permissions_list.txt"

        list_path.write_text("\n".join(sorted(bucket.keys())) + "\n", encoding="utf-8")

        if path.exists():
            existing_lines = path.read_text(encoding="utf-8").rstrip("\n").splitlines()
        else:
            existing_lines = [
                "# Generated by enum_resources --record-failed-permissions",
                f"# resource_type={resource_type}",
                f"# clean_permission_list={list_path.name}",
                "",
                "# Failures",
                "",
            ]

        summary_lines = [
            "",
            "# Summary",
            f"# unique_failed_permissions={len(bucket)}",
            "",
        ]
        summary_lines.extend(sorted(bucket.keys()))
        summary_lines.extend(["", "# Details"])
        for permission in sorted(bucket.keys()):
            details = bucket.get(permission) or {}
            count = int(details.get("count", 0))
            resources = sorted(str(item) for item in details.get("resources", set()) if str(item).strip())
            errors = sorted(str(item) for item in details.get("errors", set()) if str(item).strip())
            summary_lines.append(
                "# "
                + " | ".join(
                    part
                    for part in [
                        permission,
                        f"count={count}",
                        f"resources={','.join(resources)}" if resources else "",
                        f"errors={'; '.join(errors)}" if errors else "",
                    ]
                    if part
                )
            )
        path.write_text("\n".join(existing_lines + summary_lines) + "\n", encoding="utf-8")
        written_paths[resource_type] = str(path)
    return written_paths


def _add_iam_member(
    *,
    resource_client,
    resource_name: str,
    member: str,
    action_dict: dict[str, Any],
    brute: bool,
    role: str | None,
    debug: bool,
    get_policy,
    set_policy,
    action_scope_key: str,
    get_permission: str,
    set_permission: str,
    resource_label: str,
):
    policy_dict: dict[str, Any] = {}
    additional_binding = {"role": role, "members": [member]}

    if brute:
        print(f"[*] Overwriting {resource_name} to just be {member}")
        policy_dict["bindings"] = [additional_binding]
        policy_dict["version"] = 1
        policy = policy_dict
    else:
        print(f"[*] Fetching current policy for {resource_name}...")
        policy = get_policy(resource_client, resource_name, debug=debug)
        if not policy:
            print(
                f"{UtilityTools.RED}[X] Exiting because the current policy could not be retrieved. "
                f"Supply --overwrite to replace the entire {resource_label} IAM policy if needed."
                f"{UtilityTools.RESET}"
            )
            return -1
        if policy == 404:
            print(
                f"{UtilityTools.RED}[X] Exiting because {resource_name} does not exist. Double check the name."
                f"{UtilityTools.RESET}"
            )
            return -1

        action_dict.setdefault(action_scope_key, {}).setdefault(resource_name, set()).add(get_permission)
        policy_dict["bindings"] = list(policy.bindings)
        policy_dict["bindings"].append(additional_binding)
        policy_dict["etag"] = policy.etag
        policy_dict["version"] = policy.version
        policy = policy_dict

    print(f"[*] New policy below being added to {resource_name}\n{policy_dict.get('bindings', [])}")
    status = set_policy(resource_client, resource_name, policy, debug=debug)
    if not status:
        return status
    if status == 404:
        print(
            f"{UtilityTools.RED}[X] Exiting because {resource_name} does not exist. Double check the name."
            f"{UtilityTools.RESET}"
        )
        return -1

    action_dict.setdefault(action_scope_key, {}).setdefault(resource_name, set()).add(set_permission)
    return status


def add_project_iam_member(project_client, project_name, member, action_dict, brute=False, role=None, debug=False):
    return _add_iam_member(
        resource_client=project_client,
        resource_name=project_name,
        member=member,
        action_dict=action_dict,
        brute=bool(brute),
        role=role,
        debug=bool(debug),
        get_policy=project_get_iam_policy,
        set_policy=project_set_iam_policy,
        action_scope_key="project_permissions",
        get_permission="resourcemanager.projects.getIamPolicy",
        set_permission="resourcemanager.projects.setIamPolicy",
        resource_label="project",
    )


def add_folder_iam_member(folder_client, folder_name, member, action_dict, brute=False, role=None, debug=False):
    return _add_iam_member(
        resource_client=folder_client,
        resource_name=folder_name,
        member=member,
        action_dict=action_dict,
        brute=bool(brute),
        role=role,
        debug=bool(debug),
        get_policy=folder_get_iam_policy,
        set_policy=folder_set_iam_policy,
        action_scope_key="folder_permissions",
        get_permission="resourcemanager.folders.getIamPolicy",
        set_permission="resourcemanager.folders.setIamPolicy",
        resource_label="folder",
    )


def add_organization_iam_member(
    organization_client,
    organization_name,
    member,
    action_dict,
    brute=False,
    role=None,
    debug=False,
):
    return _add_iam_member(
        resource_client=organization_client,
        resource_name=organization_name,
        member=member,
        action_dict=action_dict,
        brute=bool(brute),
        role=role,
        debug=bool(debug),
        get_policy=organization_get_iam_policy,
        set_policy=organization_set_iam_policy,
        action_scope_key="organization_permissions",
        get_permission="resourcemanager.organizations.getIamPolicy",
        set_permission="resourcemanager.organizations.setIamPolicy",
        resource_label="organization",
    )


class _ResourceManagerBaseResource:
    TABLE_NAME = "abstract_tree_hierarchy"
    SERVICE_LABEL = "Resource Manager"
    RESOURCE_TYPE = ""
    SUMMARY_TYPE = ""
    ACTION_SCOPE_KEY = ""
    GENERAL_PERMISSION_FILE = ""
    ALL_PERMISSION_FILE = ""
    INVALID_PERMISSIONS: tuple[str, ...] = ()

    def __init__(self, session) -> None:
        self.session = session
        self.client = self._build_client()
        self._invalid_permissions: set[str] = set(self.INVALID_PERMISSIONS or ())

    def _build_client(self):
        raise NotImplementedError

    def _request(self, callback):
        return callback()

    def _save_one(self, row: Any) -> None:
        _persist_metadata_gcp(self.session, row, self.RESOURCE_TYPE)

    def save(self, rows: Iterable[Any]) -> None:
        for row in rows or []:
            self._save_one(row)

    def load_permissions(self, *, all_permissions: bool = False) -> list[str]:
        filename = self.ALL_PERMISSION_FILE if all_permissions else self.GENERAL_PERMISSION_FILE
        raw_permissions = read_lines(_permission_file(filename)) if filename else []
        all_permissions_set: set[str] = set()
        if self.ALL_PERMISSION_FILE:
            all_permissions_set = {
                str(permission or "").strip()
                for permission in read_lines(_permission_file(self.ALL_PERMISSION_FILE))
                if str(permission or "").strip()
            }
        deduped_permissions: list[str] = []
        seen: set[str] = set()
        for permission in raw_permissions:
            token = str(permission or "").strip()
            if not token or token in seen or token in self._invalid_permissions:
                continue
            if not all_permissions and all_permissions_set and token not in all_permissions_set:
                continue
            seen.add(token)
            deduped_permissions.append(token)
        return deduped_permissions

    def _register_invalid_permissions(self, error_text: str, batch_permissions: list[str]) -> set[str]:
        invalid_permissions = {
            str(match or "").strip()
            for match in INVALID_PERMISSION_RE.findall(str(error_text or ""))
            if str(match or "").strip()
        }
        if not invalid_permissions and "is not valid for this resource" in str(error_text or "") and len(batch_permissions) == 1:
            invalid_permissions = {str(batch_permissions[0] or "").strip()}
        self._invalid_permissions.update({permission for permission in invalid_permissions if permission})
        return invalid_permissions

    def resource_name(self, row: dict[str, Any] | Any) -> str:
        payload = resource_to_dict(row)
        return str(payload.get("name") or "").strip()

    def action_key(self, row: dict[str, Any] | Any) -> str:
        payload = resource_to_dict(row)
        return str(payload.get("name") or "").strip()

    def summary_rows(self, rows: Iterable[Any]) -> list[dict[str, Any]]:
        output: list[dict[str, Any]] = []
        for row in rows or []:
            payload = resource_to_dict(row)
            if not payload:
                continue
            output.append(
                {
                    "name": str(payload.get("name") or "").strip(),
                    "display_name": str(payload.get("display_name") or "").strip(),
                    "parent": str(payload.get("parent") or ""),
                    "project_id": str(payload.get("project_id") or ""),
                    "r_type": self.SUMMARY_TYPE,
                    "r_state": _resource_state_label(payload.get("state")),
                }
            )
        return output

    def record_permissions(self, action_dict: dict[str, Any], row: dict[str, Any] | Any, permissions: Iterable[str]) -> None:
        key = self.action_key(row)
        record_action_permissions(
            action_dict,
            permissions=permissions,
            scope_key=self.ACTION_SCOPE_KEY,
            scope_label=key,
        )

    def _test_permissions_once(self, *, resource_name: str, permissions: list[str], debug: bool = False) -> list[str]:
        _ = debug
        return call_test_iam_permissions(
            client=self.client,
            resource_name=resource_name,
            permissions=permissions,
            api_name=self.permission_api_name,
            service_label=self.SERVICE_LABEL,
            project_id=getattr(self.session, "project_id", None),
            not_found_label=resource_name,
            return_not_enabled=False,
        )

    @property
    def permission_api_name(self) -> str:
        raise NotImplementedError

    def test_iam_permissions(
        self,
        *,
        resource_name: str,
        permissions: list[str],
        debug: bool = False,
        batch_size: int = DEFAULT_TEST_IAM_BATCH_SIZE,
        failed_permissions: dict[str, dict[str, dict[str, Any]]] | None = None,
        show_permission_progress: bool = False,
        failed_permission_writer: FailedPermissionReportWriter | None = None,
    ) -> list[str]:
        permissions = [
            str(permission or "").strip()
            for permission in permissions or []
            if str(permission or "").strip() and str(permission or "").strip() not in self._invalid_permissions
        ]
        if not permissions:
            return []
        normalized_batch_size = max(1, int(batch_size or DEFAULT_TEST_IAM_BATCH_SIZE))
        record_failed_mode = failed_permissions is not None
        if len(permissions) <= normalized_batch_size:
            if show_permission_progress:
                if normalized_batch_size == 1:
                    print(f"[*] Testing permission 1/1 for {resource_name}: {permissions[0]}")
                else:
                    print(
                        f"[*] Testing permissions 1-{len(permissions)}/{len(permissions)} "
                        f"for {resource_name}: {', '.join(permissions)}"
                    )
            for attempt in range(1, RESOURCE_MANAGER_RATE_LIMIT_RETRY_ATTEMPTS + 1):
                try:
                    request = iam_policy_pb2.TestIamPermissionsRequest(resource=resource_name, permissions=permissions)
                    response = self._request(lambda: self.client.test_iam_permissions(request=request))
                    return list(getattr(response, "permissions", []) or [])
                except Exception as exc:
                    if _is_rate_limit_error(exc) and attempt < RESOURCE_MANAGER_RATE_LIMIT_RETRY_ATTEMPTS:
                        pause_seconds = (
                            RESOURCE_MANAGER_FAILED_PERMISSION_WINDOW_SECONDS
                            if record_failed_mode
                            else RESOURCE_MANAGER_BATCH_WINDOW_SECONDS
                        )
                        label = permissions[0] if len(permissions) == 1 and permissions else f"batch {permissions[:3]}"
                        print(
                            f"[*] Hit Resource Manager TestIamPermissions quota for {resource_name} "
                            f"while checking {label}; pausing {pause_seconds}s before retry {attempt + 1}/"
                            f"{RESOURCE_MANAGER_RATE_LIMIT_RETRY_ATTEMPTS}"
                        )
                        time.sleep(pause_seconds)
                        continue
                    if _is_rate_limit_error(exc):
                        result = handle_service_error(
                            exc,
                            api_name=self.permission_api_name,
                            resource_name=resource_name,
                            service_label=self.SERVICE_LABEL,
                            project_id=getattr(self.session, "project_id", None),
                            not_found_label=resource_name,
                            return_not_enabled=False,
                        )
                        return [] if result in (None, "Not Enabled") else list(result or [])

                    error_text = str(exc)
                    if "is not valid for this resource" in error_text:
                        invalid_permissions = self._register_invalid_permissions(error_text, permissions)
                        if failed_permissions is not None and invalid_permissions:
                            record_failed_permissions(
                                failed_permissions,
                                resource_type=self.RESOURCE_TYPE,
                                resource_name=resource_name,
                                permissions=sorted(invalid_permissions),
                                error=error_text,
                                report_writer=failed_permission_writer,
                            )
                        if len(permissions) > 1:
                            filtered_permissions = [permission for permission in permissions if permission not in invalid_permissions]
                            if filtered_permissions and len(filtered_permissions) != len(permissions):
                                return self.test_iam_permissions(
                                    resource_name=resource_name,
                                    permissions=filtered_permissions,
                                    debug=debug,
                                    batch_size=min(normalized_batch_size, len(filtered_permissions)),
                                    failed_permissions=failed_permissions,
                                    show_permission_progress=False,
                                    failed_permission_writer=failed_permission_writer,
                                )
                        return []
                    if record_failed_mode and normalized_batch_size > 1:
                        print(
                            f"[*] TestIamPermissions batch failed for {resource_name}; "
                            f"retrying the {len(permissions)} permissions individually to isolate errors"
                        )
                        granted: set[str] = set()
                        for permission in permissions:
                            granted.update(
                                self.test_iam_permissions(
                                    resource_name=resource_name,
                                    permissions=[permission],
                                    debug=debug,
                                    batch_size=1,
                                    failed_permissions=failed_permissions,
                                    show_permission_progress=False,
                                    failed_permission_writer=failed_permission_writer,
                                )
                            )
                        return sorted(granted)
                    if failed_permissions is not None:
                        record_failed_permissions(
                            failed_permissions,
                            resource_type=self.RESOURCE_TYPE,
                            resource_name=resource_name,
                            permissions=permissions,
                            error=error_text,
                            report_writer=failed_permission_writer,
                        )
                        if "is not valid for this resource" in error_text:
                            return []
                    result = handle_service_error(
                        exc,
                        api_name=self.permission_api_name,
                        resource_name=resource_name,
                        service_label=self.SERVICE_LABEL,
                        project_id=getattr(self.session, "project_id", None),
                        not_found_label=resource_name,
                        return_not_enabled=False,
                    )
                    return [] if result in (None, "Not Enabled") else list(result or [])

        granted: set[str] = set()
        batches = [
            permissions[index:index + normalized_batch_size]
            for index in range(0, len(permissions), normalized_batch_size)
        ]
        total_batches = len(batches)
        if record_failed_mode:
            throttle_calls_per_window = RESOURCE_MANAGER_FAILED_PERMISSION_CALLS_PER_WINDOW
            throttle_window_seconds = RESOURCE_MANAGER_FAILED_PERMISSION_WINDOW_SECONDS
        else:
            throttle_calls_per_window = RESOURCE_MANAGER_BATCH_CALLS_PER_WINDOW
            throttle_window_seconds = RESOURCE_MANAGER_BATCH_WINDOW_SECONDS
        rate_calls_per_min = (throttle_calls_per_window * 60.0) / float(throttle_window_seconds)
        for index, batch in enumerate(batches, start=1):
            if show_permission_progress and batch:
                start_index = ((index - 1) * normalized_batch_size) + 1
                end_index = min(index * normalized_batch_size, len(permissions))
                if normalized_batch_size == 1:
                    print(f"[*] Testing permission {index}/{total_batches} for {resource_name}: {batch[0]}")
                else:
                    print(
                        f"[*] Testing permissions {start_index}-{end_index}/{len(permissions)} "
                        f"for {resource_name}: {', '.join(batch)}"
                    )
            granted.update(
                self.test_iam_permissions(
                    resource_name=resource_name,
                    permissions=batch,
                    debug=debug,
                    batch_size=normalized_batch_size,
                    failed_permissions=failed_permissions,
                    show_permission_progress=False,
                    failed_permission_writer=failed_permission_writer,
                )
            )
            if record_failed_mode:
                if index % RESOURCE_MANAGER_FAILED_PERMISSION_CALLS_PER_WINDOW == 0 and index < total_batches:
                    remaining_batches = total_batches - index
                    pause_windows_remaining = (
                        remaining_batches + RESOURCE_MANAGER_FAILED_PERMISSION_CALLS_PER_WINDOW - 1
                    ) // RESOURCE_MANAGER_FAILED_PERMISSION_CALLS_PER_WINDOW
                    approx_minutes_remaining = (
                        pause_windows_remaining * RESOURCE_MANAGER_FAILED_PERMISSION_WINDOW_SECONDS
                    ) / 60.0
                    print(
                        f"[*] Completed {index}/{len(batches)} record-failed TestIamPermissions calls for "
                        f"{resource_name}; pausing {RESOURCE_MANAGER_FAILED_PERMISSION_WINDOW_SECONDS}s "
                        f"(batch_size={normalized_batch_size}, rate≈{rate_calls_per_min:.2f} calls/min, "
                        f"ETA≈{approx_minutes_remaining:.1f} min)"
                    )
                    time.sleep(RESOURCE_MANAGER_FAILED_PERMISSION_WINDOW_SECONDS)
            elif index % RESOURCE_MANAGER_BATCH_CALLS_PER_WINDOW == 0 and index < total_batches:
                remaining_batches = total_batches - index
                pause_windows_remaining = (
                    remaining_batches + RESOURCE_MANAGER_BATCH_CALLS_PER_WINDOW - 1
                ) // RESOURCE_MANAGER_BATCH_CALLS_PER_WINDOW
                approx_minutes_remaining = (pause_windows_remaining * RESOURCE_MANAGER_BATCH_WINDOW_SECONDS) / 60.0
                print(
                    f"[*] Completed {index}/{len(batches)} TestIamPermissions batches for {resource_name}; "
                    f"pausing {RESOURCE_MANAGER_BATCH_WINDOW_SECONDS}s "
                    f"(batch_size={normalized_batch_size}, rate≈{rate_calls_per_min:.2f} calls/min, "
                    f"ETA≈{approx_minutes_remaining:.1f} min)"
                )
                time.sleep(RESOURCE_MANAGER_BATCH_WINDOW_SECONDS)
        return sorted(granted)

    def search(self, *, debug: bool = False):
        raise NotImplementedError

    def list(self, *, parent: str, debug: bool = False):
        raise NotImplementedError

    def get(self, *, name: str, debug: bool = False, quiet_not_found: bool = False):
        raise NotImplementedError

class ResourceManagerOrganizationsResource(_ResourceManagerBaseResource):
    RESOURCE_TYPE = "organization"
    SUMMARY_TYPE = "Org"
    ACTION_SCOPE_KEY = "organization_permissions"
    GENERAL_PERMISSION_FILE = "general_organization_permissions.txt"
    ALL_PERMISSION_FILE = "all_organization_permissions.txt"

    def _build_client(self):
        return resourcemanager_v3.OrganizationsClient(credentials=self.session.credentials)

    @property
    def permission_api_name(self) -> str:
        return "resourcemanager.organizations.testIamPermissions"

    def search(self, *, debug: bool = False):
        try:
            request = resourcemanager_v3.SearchOrganizationsRequest()
            return [
                resource_to_dict(item)
                for item in self._request(lambda: self.client.search_organizations(request=request))
            ]
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.organizations.get",
                resource_name="CURRENT ORGANIZATION",
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                not_found_label="CURRENT ORGANIZATION",
                return_not_enabled=True,
            )

    def list(self, *, parent: str, debug: bool = False):
        _ = (parent, debug)
        return []

    def get(self, *, name: str, debug: bool = False, quiet_not_found: bool = False):
        try:
            request = resourcemanager_v3.GetOrganizationRequest(name=name)
            return resource_to_dict(self._request(lambda: self.client.get_organization(request=request)))
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.organizations.get",
                resource_name=name,
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                return_not_enabled=False,
                quiet_not_found=quiet_not_found,
            )


class ResourceManagerFoldersResource(_ResourceManagerBaseResource):
    RESOURCE_TYPE = "folder"
    SUMMARY_TYPE = "Folder"
    ACTION_SCOPE_KEY = "folder_permissions"
    GENERAL_PERMISSION_FILE = "general_folder_permissions.txt"
    ALL_PERMISSION_FILE = "all_folder_permissions.txt"

    def _build_client(self):
        return resourcemanager_v3.FoldersClient(credentials=self.session.credentials)

    @property
    def permission_api_name(self) -> str:
        return "resourcemanager.folders.testIamPermissions"

    def search(self, *, debug: bool = False):
        try:
            request = resourcemanager_v3.SearchFoldersRequest()
            return [
                resource_to_dict(item)
                for item in self._request(lambda: self.client.search_folders(request=request))
            ]
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.folders.get",
                resource_name="CURRENT FOLDER",
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                not_found_label="CURRENT FOLDER",
                return_not_enabled=True,
            )

    def list(self, *, parent: str, debug: bool = False):
        try:
            request = resourcemanager_v3.ListFoldersRequest(parent=parent)
            return [
                resource_to_dict(item)
                for item in self._request(lambda: self.client.list_folders(request=request))
            ]
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.folders.list",
                resource_name=parent,
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                return_not_enabled=True,
            )

    def get(self, *, name: str, debug: bool = False, quiet_not_found: bool = False):
        try:
            request = resourcemanager_v3.GetFolderRequest(name=name)
            return resource_to_dict(self._request(lambda: self.client.get_folder(request=request)))
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.folders.get",
                resource_name=name,
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                return_not_enabled=False,
                quiet_not_found=quiet_not_found,
            )


class ResourceManagerProjectsResource(_ResourceManagerBaseResource):
    RESOURCE_TYPE = "project"
    SUMMARY_TYPE = "Project"
    ACTION_SCOPE_KEY = "project_permissions"
    GENERAL_PERMISSION_FILE = "general_project_permissions.txt"
    ALL_PERMISSION_FILE = "all_project_permissions.txt"

    def _build_client(self):
        return resourcemanager_v3.ProjectsClient(credentials=self.session.credentials)

    @property
    def permission_api_name(self) -> str:
        return "resourcemanager.projects.testIamPermissions"

    def action_key(self, row: dict[str, Any] | Any) -> str:
        payload = resource_to_dict(row)
        return str(payload.get("project_id") or payload.get("name") or "").strip()

    def search(self, *, debug: bool = False):
        try:
            request = resourcemanager_v3.SearchProjectsRequest()
            return [
                resource_to_dict(item)
                for item in self._request(lambda: self.client.search_projects(request=request))
            ]
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.projects.get",
                resource_name="CURRENT PROJECT",
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                not_found_label="CURRENT PROJECT",
                return_not_enabled=True,
            )

    def list(self, *, parent: str, debug: bool = False):
        try:
            request = resourcemanager_v3.ListProjectsRequest(parent=parent)
            return [
                resource_to_dict(item)
                for item in self._request(lambda: self.client.list_projects(request=request))
            ]
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.projects.list",
                resource_name=parent,
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                return_not_enabled=True,
            )

    def get(self, *, name: str, debug: bool = False, quiet_not_found: bool = False):
        try:
            request = resourcemanager_v3.GetProjectRequest(name=name)
            return resource_to_dict(self._request(lambda: self.client.get_project(request=request)))
        except Exception as exc:
            return handle_service_error(
                exc,
                api_name="resourcemanager.projects.get",
                resource_name=name,
                service_label=self.SERVICE_LABEL,
                project_id=getattr(self.session, "project_id", None),
                return_not_enabled=False,
                quiet_not_found=quiet_not_found,
            )


def build_hierarchy_tree(
    *,
    projects_resource: ResourceManagerProjectsResource,
    folders_resource: ResourceManagerFoldersResource,
    parent_ids: Iterable[str],
    debug: bool = False,
) -> dict[str, list[dict[str, Any]]]:
    pending_parents = deque(str(parent_id or "").strip() for parent_id in parent_ids or [])
    seen_parents: set[str] = set()
    discovered_folders: list[dict[str, Any]] = []
    discovered_projects: list[dict[str, Any]] = []

    while pending_parents:
        parent_name = str(pending_parents.popleft() or "").strip()
        if not parent_name or parent_name in seen_parents:
            continue
        seen_parents.add(parent_name)

        folders = folders_resource.list(parent=parent_name, debug=debug)
        if isinstance(folders, list) and folders:
            folders_resource.save(folders)
            for folder in folders:
                payload = resource_to_dict(folder)
                if not payload:
                    continue
                discovered_folders.append(payload)
                child_name = folders_resource.resource_name(payload)
                if child_name and child_name not in seen_parents:
                    pending_parents.append(child_name)

        projects = projects_resource.list(parent=parent_name, debug=debug)
        if isinstance(projects, list) and projects:
            projects_resource.save(projects)
            for project in projects:
                payload = resource_to_dict(project)
                if payload:
                    discovered_projects.append(payload)

    deduped_folders = _dedupe_rows(discovered_folders)
    deduped_projects = _dedupe_rows(discovered_projects)
    print(
        "[*] recursive list results: "
        f"folders discovered {len(deduped_folders)}, "
        f"projects discovered {len(deduped_projects)}"
    )
    return {
        "folders": deduped_folders,
        "projects": deduped_projects,
    }


def resolve_missing_hierarchy_parents(
    session,
    *,
    folders_resource: ResourceManagerFoldersResource,
    organizations_resource: ResourceManagerOrganizationsResource,
    debug: bool = False,
) -> dict[str, list[dict[str, Any]]]:
    try:
        rows = session.get_data(
            "abstract_tree_hierarchy",
            columns=["name", "display_name", "parent"],
        ) or []
    except Exception:
        rows = []

    normalized_rows = _dedupe_rows(rows)
    rows_by_name = {
        str(row.get("name") or "").strip(): dict(row)
        for row in normalized_rows
        if str(row.get("name") or "").strip()
    }
    folder_queue: deque[str] = deque()
    org_queue: deque[str] = deque()

    def _is_placeholder_label(resource_name: str, row: dict[str, Any] | None) -> bool:
        if not row:
            return True
        display_name = str(row.get("display_name") or "").strip()
        if not display_name:
            return True
        leaf = extract_path_tail(resource_name, default=resource_name)
        return display_name in {resource_name, leaf}

    def _enqueue_if_needed(resource_name: str) -> None:
        token = str(resource_name or "").strip()
        if not token:
            return
        row = rows_by_name.get(token)
        if not _is_placeholder_label(token, row):
            return
        if token.startswith("folders/"):
            folder_queue.append(token)
        elif token.startswith("organizations/"):
            org_queue.append(token)

    for row in normalized_rows:
        name = str(row.get("name") or "").strip()
        parent = str(row.get("parent") or "").strip()
        _enqueue_if_needed(name)
        if parent and parent not in {"N/A", "None"}:
            _enqueue_if_needed(parent)

    resolved_folders: list[dict[str, Any]] = []
    resolved_orgs: list[dict[str, Any]] = []
    seen_folders: set[str] = set()
    seen_orgs: set[str] = set()

    while folder_queue:
        folder_name = folder_queue.popleft()
        if folder_name in seen_folders:
            continue
        seen_folders.add(folder_name)
        folder = folders_resource.get(name=folder_name, debug=debug, quiet_not_found=True)
        if not isinstance(folder, dict) or not folder:
            continue
        folders_resource.save([folder])
        resolved_folders.append(folder)
        parent = str(folder.get("parent") or "").strip()
        if parent:
            _enqueue_if_needed(parent)

    while org_queue:
        org_name = org_queue.popleft()
        if org_name in seen_orgs:
            continue
        seen_orgs.add(org_name)
        org = organizations_resource.get(name=org_name, debug=debug, quiet_not_found=True)
        if not isinstance(org, dict) or not org:
            continue
        organizations_resource.save([org])
        resolved_orgs.append(org)

    print(
        "[*] get_* enrichment results: "
        f"folders resolved {len(resolved_folders)}/{len(seen_folders)}, "
        f"orgs resolved {len(resolved_orgs)}/{len(seen_orgs)}"
    )
    return {
        "folders": _dedupe_rows(resolved_folders),
        "organizations": _dedupe_rows(resolved_orgs),
    }
